# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sensor.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0csensor.proto\"&\n\x0f\x41\x63tivateRequest\x12\x13\n\x0bmodule_uuid\x18\x01 \x01(\t\"8\n\x10\x41\x63tivateResponse\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x90\x01\n\x0e\x43ollectRequest\x12\x33\n\x14soil_sample_location\x18\x01 \x01(\x0b\x32\x15.CollectRequest.Point\x1aI\n\x05Point\x12\x14\n\x0cx_coordinate\x18\x01 \x01(\x02\x12\x14\n\x0cy_coordinate\x18\x02 \x01(\x02\x12\x14\n\x0cz_coordinate\x18\x03 \x01(\x02\"\"\n\x0f\x43ollectResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"i\n\x0e\x41nalyzeRequest\x12&\n\x06\x64\x65tail\x18\x01 \x01(\x0e\x32\x16.AnalyzeRequest.Detail\"/\n\x06\x44\x65tail\x12\x07\n\x03LOW\x10\x00\x12\x07\n\x03MED\x10\x01\x12\x08\n\x04HIGH\x10\x02\x12\t\n\x05ULTRA\x10\x03\"a\n\x0f\x41nalyzeResponse\x12\x16\n\x0eminerals_ratio\x18\x01 \x01(\x01\x12\x18\n\x10moisture_content\x18\x02 \x01(\x01\x12\x1c\n\x14organic_matter_ratio\x18\x03 \x01(\x01\x32\xb3\x01\n\nSoilSensor\x12\x35\n\x0e\x41\x63tivateModule\x12\x10.ActivateRequest\x1a\x11.ActivateResponse\x12\x36\n\x11\x43ollectSoilSample\x12\x0f.CollectRequest\x1a\x10.CollectResponse\x12\x36\n\x11\x41nalyzeSoilSample\x12\x0f.AnalyzeRequest\x1a\x10.AnalyzeResponseb\x06proto3'
)



_ANALYZEREQUEST_DETAIL = _descriptor.EnumDescriptor(
  name='Detail',
  full_name='AnalyzeRequest.Detail',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LOW', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MED', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='HIGH', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ULTRA', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=355,
  serialized_end=402,
)
_sym_db.RegisterEnumDescriptor(_ANALYZEREQUEST_DETAIL)


_ACTIVATEREQUEST = _descriptor.Descriptor(
  name='ActivateRequest',
  full_name='ActivateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='module_uuid', full_name='ActivateRequest.module_uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=54,
)


_ACTIVATERESPONSE = _descriptor.Descriptor(
  name='ActivateResponse',
  full_name='ActivateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status_code', full_name='ActivateResponse.status_code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='ActivateResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=112,
)


_COLLECTREQUEST_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='CollectRequest.Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x_coordinate', full_name='CollectRequest.Point.x_coordinate', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y_coordinate', full_name='CollectRequest.Point.y_coordinate', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='z_coordinate', full_name='CollectRequest.Point.z_coordinate', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=259,
)

_COLLECTREQUEST = _descriptor.Descriptor(
  name='CollectRequest',
  full_name='CollectRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='soil_sample_location', full_name='CollectRequest.soil_sample_location', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_COLLECTREQUEST_POINT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=259,
)


_COLLECTRESPONSE = _descriptor.Descriptor(
  name='CollectResponse',
  full_name='CollectResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='CollectResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=261,
  serialized_end=295,
)


_ANALYZEREQUEST = _descriptor.Descriptor(
  name='AnalyzeRequest',
  full_name='AnalyzeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='detail', full_name='AnalyzeRequest.detail', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ANALYZEREQUEST_DETAIL,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=297,
  serialized_end=402,
)


_ANALYZERESPONSE = _descriptor.Descriptor(
  name='AnalyzeResponse',
  full_name='AnalyzeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='minerals_ratio', full_name='AnalyzeResponse.minerals_ratio', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='moisture_content', full_name='AnalyzeResponse.moisture_content', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='organic_matter_ratio', full_name='AnalyzeResponse.organic_matter_ratio', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=404,
  serialized_end=501,
)

_COLLECTREQUEST_POINT.containing_type = _COLLECTREQUEST
_COLLECTREQUEST.fields_by_name['soil_sample_location'].message_type = _COLLECTREQUEST_POINT
_ANALYZEREQUEST.fields_by_name['detail'].enum_type = _ANALYZEREQUEST_DETAIL
_ANALYZEREQUEST_DETAIL.containing_type = _ANALYZEREQUEST
DESCRIPTOR.message_types_by_name['ActivateRequest'] = _ACTIVATEREQUEST
DESCRIPTOR.message_types_by_name['ActivateResponse'] = _ACTIVATERESPONSE
DESCRIPTOR.message_types_by_name['CollectRequest'] = _COLLECTREQUEST
DESCRIPTOR.message_types_by_name['CollectResponse'] = _COLLECTRESPONSE
DESCRIPTOR.message_types_by_name['AnalyzeRequest'] = _ANALYZEREQUEST
DESCRIPTOR.message_types_by_name['AnalyzeResponse'] = _ANALYZERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ActivateRequest = _reflection.GeneratedProtocolMessageType('ActivateRequest', (_message.Message,), {
  'DESCRIPTOR' : _ACTIVATEREQUEST,
  '__module__' : 'sensor_pb2'
  # @@protoc_insertion_point(class_scope:ActivateRequest)
  })
_sym_db.RegisterMessage(ActivateRequest)

ActivateResponse = _reflection.GeneratedProtocolMessageType('ActivateResponse', (_message.Message,), {
  'DESCRIPTOR' : _ACTIVATERESPONSE,
  '__module__' : 'sensor_pb2'
  # @@protoc_insertion_point(class_scope:ActivateResponse)
  })
_sym_db.RegisterMessage(ActivateResponse)

CollectRequest = _reflection.GeneratedProtocolMessageType('CollectRequest', (_message.Message,), {

  'Point' : _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), {
    'DESCRIPTOR' : _COLLECTREQUEST_POINT,
    '__module__' : 'sensor_pb2'
    # @@protoc_insertion_point(class_scope:CollectRequest.Point)
    })
  ,
  'DESCRIPTOR' : _COLLECTREQUEST,
  '__module__' : 'sensor_pb2'
  # @@protoc_insertion_point(class_scope:CollectRequest)
  })
_sym_db.RegisterMessage(CollectRequest)
_sym_db.RegisterMessage(CollectRequest.Point)

CollectResponse = _reflection.GeneratedProtocolMessageType('CollectResponse', (_message.Message,), {
  'DESCRIPTOR' : _COLLECTRESPONSE,
  '__module__' : 'sensor_pb2'
  # @@protoc_insertion_point(class_scope:CollectResponse)
  })
_sym_db.RegisterMessage(CollectResponse)

AnalyzeRequest = _reflection.GeneratedProtocolMessageType('AnalyzeRequest', (_message.Message,), {
  'DESCRIPTOR' : _ANALYZEREQUEST,
  '__module__' : 'sensor_pb2'
  # @@protoc_insertion_point(class_scope:AnalyzeRequest)
  })
_sym_db.RegisterMessage(AnalyzeRequest)

AnalyzeResponse = _reflection.GeneratedProtocolMessageType('AnalyzeResponse', (_message.Message,), {
  'DESCRIPTOR' : _ANALYZERESPONSE,
  '__module__' : 'sensor_pb2'
  # @@protoc_insertion_point(class_scope:AnalyzeResponse)
  })
_sym_db.RegisterMessage(AnalyzeResponse)



_SOILSENSOR = _descriptor.ServiceDescriptor(
  name='SoilSensor',
  full_name='SoilSensor',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=504,
  serialized_end=683,
  methods=[
  _descriptor.MethodDescriptor(
    name='ActivateModule',
    full_name='SoilSensor.ActivateModule',
    index=0,
    containing_service=None,
    input_type=_ACTIVATEREQUEST,
    output_type=_ACTIVATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CollectSoilSample',
    full_name='SoilSensor.CollectSoilSample',
    index=1,
    containing_service=None,
    input_type=_COLLECTREQUEST,
    output_type=_COLLECTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='AnalyzeSoilSample',
    full_name='SoilSensor.AnalyzeSoilSample',
    index=2,
    containing_service=None,
    input_type=_ANALYZEREQUEST,
    output_type=_ANALYZERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SOILSENSOR)

DESCRIPTOR.services_by_name['SoilSensor'] = _SOILSENSOR

# @@protoc_insertion_point(module_scope)
